### ISSUE TITLE
Вопрос:

### ISSUE THREAD

**Issue by mkurtm** [SoftAlgoTrade/TradingStrategies#2]

**Comment by mkurtm** [comment]
Можно ли добавить в индикаторы каналы кельтнера? Формула SMA - ATR * K, K - коэффициент.
Думаю, можно это сделать простым вычитанием одной серии из другой прямо в скрипте. Но думаю, он достоин чтобы войти в набор индикаторов.

**Comment by SoftAlgoTrade** [comment]
Да, хороший индикатор, мы уже добавили его в стандартный набор индикаторов - KeltnerChannelTop, KeltnerChannelBottom.
